- name: deps
  with_items: '{{ docker_deps }}'
  package:
    name: '{{ item }}'
    state: present
  tags:
    - docker

- name: key1
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  tags:
    - docker

- name: key2
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
  tags:
    - docker

- name: repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    update_cache: yes
    state: present
  tags:
    - docker

- name: install
  with_items: '{{ docker_packages }}'
  package:
    name: '{{ item }}'
    state: present
  tags:
    - docker

- name: service
  notify:
    - restart docker
  template:
    src: service.j2
    dest: /etc/systemd/system/docker.service
  tags:
    - docker

- name: default config
  notify:
    - restart docker
  template:
    src: default.j2
    dest: /etc/default/docker
  tags:
    - docker

- name: daemon config
  notify:
    - restart docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  tags:
    - docker

- name: start
  with_items: '{{ docker_services }}'
  systemd:
    name: '{{ item }}'
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - docker

- name: compose
  get_url:
    url: '{{ docker_compose_url }}'
    dest: /usr/local/bin/docker-compose
    checksum: sha1:{{ docker_compose_checksum }}
    mode: u=rwx,g=rx,o=rx
    validate_certs: false
  tags:
    - docker
